### PR TITLE
Added functionality to allow a topic decider and a custom formatter

### PR DESCRIPTION
**Pull request by dahlsailrunner**
Hi there - this sink looks like just what I need, but I'd like to both be able to write different log entries to different topics, and I'd like to use my own formatter for these.  The PR is a fairly light touch but implements both of those features.

Let me know if this might be acceptable or if more changes would be required.  Also, I'd be happy to add some notes to the readme if this looks ok.

### CODE REVIEW

**Comment by jonhoare** [comment]
Hey @dahlsailrunner! Thanks for the PR!

This seems like a great addition. To be honest this was my lazy coding as we didn't need to configure ITextFormatter for our instance when I wrote this intially.

If you could just add something to the readme about it then yeah I'm happy to approve and merge this. 👍

**Review by jonhoare — COMMENTED** [review]
Also, your PR has reminded me that I had outstanding dependabot PR's to merge. Would you mind rebasing your changes as well, to pick up the merged dependency changes, and then we'll be good to merge this PR

**Comment by dahlsailrunner** [comment]
I believe I've done everything to make this ready to go (outside of providing new versions or however you have that set up).  I've pulled in your dependabot changes and added info to the readme.  Let me know if anything else is needed.  And thanks!  :)

**Review by jonhoare — APPROVED** [review]
Thanks! That looks all good! I'll merge it in now and tag a new version for you 👍

**Pull request merged**
